// flow-typed signature: 679cd26b5bbc3b9b282fa7bfad31baa0
// flow-typed version: <<STUB>>/react-motion_v0.4.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-motion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-motion/build/react-motion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/mapToZero' {
  declare module.exports: any;
}

declare module 'react-motion/lib/mergeDiff' {
  declare module.exports: any;
}

declare module 'react-motion/lib/Motion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/presets' {
  declare module.exports: any;
}

declare module 'react-motion/lib/react-motion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/reorderKeys' {
  declare module.exports: any;
}

declare module 'react-motion/lib/shouldStopAnimation' {
  declare module.exports: any;
}

declare module 'react-motion/lib/spring' {
  declare module.exports: any;
}

declare module 'react-motion/lib/StaggeredMotion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/stepper' {
  declare module.exports: any;
}

declare module 'react-motion/lib/stripStyle' {
  declare module.exports: any;
}

declare module 'react-motion/lib/TransitionMotion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/Types' {
  declare module.exports: any;
}

declare module 'react-motion/src/mapToZero' {
  declare module.exports: any;
}

declare module 'react-motion/src/mergeDiff' {
  declare module.exports: any;
}

declare module 'react-motion/src/Motion' {
  declare module.exports: any;
}

declare module 'react-motion/src/presets' {
  declare module.exports: any;
}

declare module 'react-motion/src/react-motion' {
  declare module.exports: any;
}

declare module 'react-motion/src/reorderKeys' {
  declare module.exports: any;
}

declare module 'react-motion/src/shouldStopAnimation' {
  declare module.exports: any;
}

declare module 'react-motion/src/spring' {
  declare module.exports: any;
}

declare module 'react-motion/src/StaggeredMotion' {
  declare module.exports: any;
}

declare module 'react-motion/src/stepper' {
  declare module.exports: any;
}

declare module 'react-motion/src/stripStyle' {
  declare module.exports: any;
}

declare module 'react-motion/src/TransitionMotion' {
  declare module.exports: any;
}

declare module 'react-motion/src/Types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-motion/build/react-motion.js' {
  declare module.exports: $Exports<'react-motion/build/react-motion'>;
}
declare module 'react-motion/lib/mapToZero.js' {
  declare module.exports: $Exports<'react-motion/lib/mapToZero'>;
}
declare module 'react-motion/lib/mergeDiff.js' {
  declare module.exports: $Exports<'react-motion/lib/mergeDiff'>;
}
declare module 'react-motion/lib/Motion.js' {
  declare module.exports: $Exports<'react-motion/lib/Motion'>;
}
declare module 'react-motion/lib/presets.js' {
  declare module.exports: $Exports<'react-motion/lib/presets'>;
}
declare module 'react-motion/lib/react-motion.js' {
  declare module.exports: $Exports<'react-motion/lib/react-motion'>;
}
declare module 'react-motion/lib/reorderKeys.js' {
  declare module.exports: $Exports<'react-motion/lib/reorderKeys'>;
}
declare module 'react-motion/lib/shouldStopAnimation.js' {
  declare module.exports: $Exports<'react-motion/lib/shouldStopAnimation'>;
}
declare module 'react-motion/lib/spring.js' {
  declare module.exports: $Exports<'react-motion/lib/spring'>;
}
declare module 'react-motion/lib/StaggeredMotion.js' {
  declare module.exports: $Exports<'react-motion/lib/StaggeredMotion'>;
}
declare module 'react-motion/lib/stepper.js' {
  declare module.exports: $Exports<'react-motion/lib/stepper'>;
}
declare module 'react-motion/lib/stripStyle.js' {
  declare module.exports: $Exports<'react-motion/lib/stripStyle'>;
}
declare module 'react-motion/lib/TransitionMotion.js' {
  declare module.exports: $Exports<'react-motion/lib/TransitionMotion'>;
}
declare module 'react-motion/lib/Types.js' {
  declare module.exports: $Exports<'react-motion/lib/Types'>;
}
declare module 'react-motion/src/mapToZero.js' {
  declare module.exports: $Exports<'react-motion/src/mapToZero'>;
}
declare module 'react-motion/src/mergeDiff.js' {
  declare module.exports: $Exports<'react-motion/src/mergeDiff'>;
}
declare module 'react-motion/src/Motion.js' {
  declare module.exports: $Exports<'react-motion/src/Motion'>;
}
declare module 'react-motion/src/presets.js' {
  declare module.exports: $Exports<'react-motion/src/presets'>;
}
declare module 'react-motion/src/react-motion.js' {
  declare module.exports: $Exports<'react-motion/src/react-motion'>;
}
declare module 'react-motion/src/reorderKeys.js' {
  declare module.exports: $Exports<'react-motion/src/reorderKeys'>;
}
declare module 'react-motion/src/shouldStopAnimation.js' {
  declare module.exports: $Exports<'react-motion/src/shouldStopAnimation'>;
}
declare module 'react-motion/src/spring.js' {
  declare module.exports: $Exports<'react-motion/src/spring'>;
}
declare module 'react-motion/src/StaggeredMotion.js' {
  declare module.exports: $Exports<'react-motion/src/StaggeredMotion'>;
}
declare module 'react-motion/src/stepper.js' {
  declare module.exports: $Exports<'react-motion/src/stepper'>;
}
declare module 'react-motion/src/stripStyle.js' {
  declare module.exports: $Exports<'react-motion/src/stripStyle'>;
}
declare module 'react-motion/src/TransitionMotion.js' {
  declare module.exports: $Exports<'react-motion/src/TransitionMotion'>;
}
declare module 'react-motion/src/Types.js' {
  declare module.exports: $Exports<'react-motion/src/Types'>;
}
